- name: Disable default redis module
  ansible.builtin.command: dnf module disable redis -y
- name: Enabling redis:7
  ansible.builtin.command: dnf module enable redis:7 -y
- name: Installing redis
  ansible.builtin.dnf:
    name: redis
    state: present
- name: Replace bind IP
  ansible.builtin.replace:
    path: /etc/redis/redis.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'
- name: replace line in conf file
  ansible.builtin.lineinfile:
    path: /etc/redis/redis.conf
    regexp: 'protected-mode'
    line: protected-mode no
- name: start and enable redis
  ansible.builtin.service:
    name: redis
    state: started
    enabled: yes
