- name: Creating system User
  ansible.builtin.user:
    name: roboshop
    comment: Roboshop system user
    shell: /sbin/nologin
    system: true
    home: /app
- name: create directory
  ansible.builtin.file:
    path: /app
    state: directory
- name: Downloading zip file
  ansible.builtin.get_url:
    url: https://roboshop-artifacts.s3.amazonaws.com/catalogue-v3.zip 
    dest: /tmp/catalogue.zip
- name: Unzipping the file
  ansible.builtin.unarchive:
    src: /tmp/catalogue.zip
    dest: /app
    remote_src: yes