- name: Installing maven 
  ansible.builtin.dnf:
    name: "{{ item }}"  
    state: present
  loop:
  - maven
  - mysql

- name: Installing Python Packages
  ansible.builtin.pip:
    name: "{{ item }}"
    executable: pip3.9
  loop:
  - cryptography
  - PyMySQL
- name: Install dependencies
  ansible.builtin.command: mvn clean package
  args:
    chdir: /app

- name: Moving and renaming Jar file
  ansible.builtin.command: mv target/shipping-1.0.jar shipping.jar
  args:
    chdir: /app